name: build
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs
      - run: pip install mkdocs-click
      - run: pip install -r requirements.txt
      - run: export PYTHONPATH=$(pwd)
      - run: bash -c "PYTHONPATH=$PWD mkdocs gh-deploy --force --clean --verbose"